### ISSUE TITLE
Turns and scores

### ISSUE THREAD

**Issue by joereynolds** [joereynolds/Mr-Figs#45]
Each level should have an A+ score criteria which is the number of turns you must take in order to get A+.

### TODO

- [x] - Keep track of players turns in `actory.py`
- [x] - Display number of turns taken by player so far (should go in sidebar)
- [x] - Display number of turns required to ace current level (map.properties for this?) (should go in sidebar)
